# Generated by Django 2.0.3 on 2018-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, upload_to='albumCover/'),
        ),
    ]
