# Generated by Django 2.0.3 on 2018-04-05 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0003_auto_20180403_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='albummember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='albummember',
            name='album',
        ),
        migrations.RemoveField(
            model_name='albummember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='album',
            name='members',
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(upload_to='albumCover/'),
        ),
        migrations.DeleteModel(
            name='AlbumMember',
        ),
        migrations.AddField(
            model_name='albumlike',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likeUnlike', to='albums.Album'),
        ),
        migrations.AddField(
            model_name='albumlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(through='albums.AlbumLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='albumlike',
            unique_together={('album', 'user')},
        ),
    ]
