# Generated by Django 2.0.3 on 2018-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180403_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(unique=True, upload_to='photos/'),
        ),
    ]
